---
version: "2.0"

services:
  worker:
    image: ghcr.io/h06nwawo/ikarozz-worker:latest
    expose:
      - port: 8188
        as: 80
        to:
          - global: true
    env:
      - HUGGING_FACE_HUB_TOKEN=YOUR_HF_TOKEN_HERE

profiles:
  compute:
    worker:
      resources:
        cpu:
          units: 8
        memory:
          size: 32Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: h200
        storage:
          - size: 100Gi

  placement:
    akash:
      pricing:
        worker:
          denom: uakt
          amount: 10000

deployment:
  worker:
    akash:
      profile: worker
      count: 1
